# -*- coding: utf-8 -*-
{
    'name': 'Citas Hospital Santa Rosa',
    'version': '18.0.1.0.0',
    'category': 'Healthcare',
    'summary': 'Sistema de gestion de citas medicas y recetas',
    'author': 'Hospital Santa Rosa',
    'website': 'https://www.hospitalsantarosa.com',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'calendar',
        'web',
        'hr',
        'portal',
        'website',
        'product',
        'stock',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/mail_template.xml',
        'data/cron_jobs.xml',
        
        'views/hospital_patient_views.xml',
        'views/hospital_doctor_views.xml',
        'views/hospital_specialty_views.xml',
        'views/hospital_appointment_views.xml',
        'views/hospital_schedule_views.xml',
        'views/hospital_prescription_views.xml',
        'views/product_product_views.xml',
        'views/dashboard_views.xml',
        'views/menu.xml',
        'wizard/appointment_cancel_wizard_views.xml',
        'reports/prescription_report.xml',
        'reports/appointment_report.xml',
        'views/portal_templates.xml',
        'views/website_templates.xml',
        'data/demo_data.xml',
    ],
    'demo': [
        'data/demo_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'citas_hospital/static/src/css/dashboard.css',
            'citas_hospital/static/src/js/appointment_booking.js',
        ],
        'web.assets_frontend': [
            'citas_hospital/static/src/css/website.css',
            'citas_hospital/static/src/js/website_booking.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
